version: '3'

services:
  rabbitmq:
    container_name: "rabbitmq-btg"  
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 
      RABBITMQ_DEFAULT_PASS: 

  mongo:
    container_name: "mongo-btg"  
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - MongoDB:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 
    networks:
      - mongo-compose-network
    
  mongo-express:
    container_name: "mongo-express-btg"  
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: 
      ME_CONFIG_BASICAUTH_PASSWORD: 
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_MONGODB_SERVER: mongo
    links:
      - mongo
    networks:
      - mongo-compose-network
  
volumes:
  rabbitmq_data:

networks: 
    mongo-compose-network:
      driver: bridge